trigger:
- test

pool:
  vmImage: ubuntu-latest

variables:
- group: FabricService

- name: ACR_NAME
  value: cluedindev

- name: containerAppName
  value: backend-api

- name: IMAGE_TAG
  value: $(Build.BuildId)

- name: ENVIRONMENT
  value: test

stages:
  - stage: Build
    displayName: "Build & Push Docker Image"
    jobs:
      - job: BuildAndPush
        displayName: "Build .NET + Docker"
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.0.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: |
              dotnet build Fabric_Extension_BE_Boilerplate.sln --configuration Release
            displayName: "Build .NET Backend"
          - task: PowerShell@2
            displayName: 'Login to Azure with Service Principal'
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                az login --service-principal `
                  --username $env:AZURE_CLIENT_ID `
                  --password $env:AZURE_CLIENT_SECRET `
                  --tenant $env:AZURE_TENANT_ID
            env:
              AZURE_CLIENT_ID: $(service.Azure.ClientId)
              AZURE_CLIENT_SECRET: $(service.Azure.ClientSecret)
              AZURE_TENANT_ID: $(service.Azure.TenantId)
          - task: AzureCLI@2
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az acr login --name $(ACR_NAME)
                docker build -t $(ACR_NAME).azurecr.io/$(CONTAINER_APP_NAME):$(IMAGE_TAG) .
                docker push $(ACR_NAME).azurecr.io/$(CONTAINER_APP_NAME):$(IMAGE_TAG)
  - stage: DEPLOY_STAGE_DEVELOP
    displayName: "Deploy Fabric Backend - Dev"
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'test'))
    variables:
      - name: environment
        value: "test"
    jobs:
      - template: ./templates/deploy-infrastructure.yml
        parameters:
          environment: $(environment)
          deploymentEnvironment: fabric-dev
          terraformStorage: $(service.Terraform.StorageAccount)
          terraformContainer: $(service.Terraform.Container)
          terraformAccessKey: $(service.Terraform.AccessKey)
          terraformDir: $(System.DefaultWorkingDirectory)/Backend/terraform
          terraformOutputPath: $(Pipeline.Workspace)/Backend/terraform/$(environment)
          terraformPlanPath: $(Pipeline.Workspace)/Backend/terraform/$(environment)/tfplan
          subscriptionId: $(service.Azure.SubscriptionId)
          clientId: $(service.Azure.ClientId)
          clientSecret: $(service.Azure.ClientSecret)
          tenantId: $(service.Azure.TenantId)
          location: $(service.Develop.Location)
          resourceGroupName: $(service.Develop.ResourceGroupName)
          dockerImage: $(service.shared.DockerImage)
