trigger:
- test

pool:
  vmImage: ubuntu-latest

variables:
- group: FabricService

- name: ACR_NAME
  value: cluedindev

- name: containerAppName
  value: backend-api

- name: IMAGE_TAG
  value: $(Build.BuildId)

- name: ENVIRONMENT
  value: test

stages:
  - stage: Build
    displayName: "Build & Push Docker Image"
    jobs:
      - job: BuildAndPush
        displayName: "Build .NET + Docker"
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.0.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: |
              cd src/backend-api
              dotnet restore
              dotnet build --configuration Release
              dotnet publish -c Release -o publish
            displayName: "Build .NET Backend"

          - task: Docker@2
            displayName: "Build Docker Image"
            inputs:
              containerRegistry: 'CluedIn Docker Hub'
              repository: "$(ACR_NAME).azurecr.io/backend-api"
              command: "buildAndPush"
              Dockerfile: "src/backend-api/Dockerfile"
              buildContext: "src/backend-api"
              tags: |
                $(IMAGE_TAG)

  - stage: DEPLOY_STAGE_DEVELOP
    displayName: "Deploy Fabric Backend - Dev"
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'test'))
    variables:
      - name: environment
        value: "test"
    jobs:
      - template: ./templates/deploy-infrastructure.yml
        parameters:
          environment: $(environment)
          deploymentEnvironment: fabric-dev
          terraformStorage: $(service.Terraform.StorageAccount)
          terraformContainer: $(service.Terraform.Container)
          terraformAccessKey: $(service.Terraform.AccessKey)
          terraformDir: $(System.DefaultWorkingDirectory)/Backend/terraform
          terraformOutputPath: $(Pipeline.Workspace)/Backend/terraform/$(environment)
          terraformPlanPath: $(Pipeline.Workspace)/Backend/terraform/$(environment)/tfplan
          subscriptionId: $(service.Azure.SubscriptionId)
          clientId: $(service.Azure.ClientId)
          clientSecret: $(service.Azure.ClientSecret)
          tenantId: $(service.Azure.TenantId)
          location: $(service.Develop.Location)
          resourceGroupName: $(service.Develop.ResourceGroupName)
          dockerImage: $(service.shared.DockerImage)
